### ISSUE TITLE
Refactor application for reusability

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/static-tables#18]
We want to use this application to serve up multiple sites with limited functionality like displaying a table of data.

Tasks to accomplish:

- [x] #20
- [x] https://github.com/pulibrary/marquand-catalogs/issues/21
- [x] https://github.com/pulibrary/marquand-catalogs/issues/23
- [x] https://github.com/pulibrary/marquand-catalogs/issues/24
- [x] Allow the PaginatedTable.js component to configure sorting order https://github.com/pulibrary/marquand-catalogs/pull/19
